services:
  mongodb:
    image: mongo:8-noble
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=compare-it
    volumes:
      - mongodb-data:/data/db

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "2525:25"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - smtp4dev
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/compare-it?authSource=admin

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production

volumes:
  mongodb-data:
