services:
  mongodb:
    image: mongo:8-noble
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=compare-it
    volumes:
      - mongodb-data:/data/db

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "5000:80"
      - "2525:25"

volumes:
  mongodb-data:
