FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

RUN apk --no-cache add chromium chromium-chromedriver

COPY gradle gradle
COPY gradlew build.gradle.kts settings.gradle.kts .

RUN chmod +x ./gradlew && ./gradlew dependencies --no-daemon

COPY . .

EXPOSE 8080

ENTRYPOINT [ "./gradlew" ]

CMD ["bootRun", "--no-daemon"]
