spring:
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/compare-it?authSource=admin

  mail:
    host: smtp4dev
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://compare-it.eu.auth0.com/

logging:
  level:
    web: debug
    data: debug
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
            repository:
              query: debug

cors:
  allowed-origins: "*"
