spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/compare-it?authSource=admin

  mail:
    host: localhost
    port: 2525
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

logging:
  level:
    web: debug
    data: debug
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
            repository:
              query: debug
