spring:
  application:
    name: backend

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 50

    mongodb:
      connect-timeout: 30_000
      socket-timeout: 30_000
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api/docs

  swagger-ui:
    path: /swagger-ui.html

  error:
    include-message: always
    include-path: never

cors:
  allowed-headers: "*"
  allowed-methods: "*"
