spring:
  mail:
    host: smtp4dev
    port: 25
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://compare-it.eu.auth0.com

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

logging:
  level:
    root: error

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      access: unrestricted
